from enum import Enum

class ModifierEnum(Enum):
    NONE = None
    STRENGTH = "Strength"
    SPECIAL = "Special"
    INSIGHT = "Insight"
    DEXTERITY = "Dexterity"
    FIGHT = "Fight"
    BRAWL = "Brawl"
    CONTEST = "Contest"
    PERFORM = "Perform"
    CHANNEL = "Channel"
    ALERT = "Alert"
    TOUGH = "Tough"
    INTIMIDATE = "Intimidate"
    CUTE = "Cute"
    ALLURE = "Allure"
    NATURE = "Nature"
    SURVIVAL = "Survival"
    WILL = "Will"
    SMART = "Smart"
    BEAUTY = "Beauty"
    COOL = "Cool"
    EVASION = "Evasion"
    TOUGH_CUTE = "Tough/Cute"
