from enum import Enum

class ModifierEnum(Enum):
    Dexterity = "Dexterity"
    Fight = "Fight"
    Brawl = "Brawl"
    Contest = "Contest"
    Perform = "Perform"
    Channel = "Channel"
    Tough = "Tough"
    Intimidate = "Intimidate"
    Cute = "Cute"
    Allure = "Allure"
    Nature = "Nature"
    Survival = "Survival"
    Insight = "Insight"
    Will = "Will"
    Smart = "Smart"
    Beauty = "Beauty"
    Cool = "Cool"
    Evasion = "Evasion"
    Tough_Cute = "Tough/Cute"
